name: pull request
on: pull_request
jobs:
  status-check:
    runs-on: ubuntu-24.04
    if: failure()
    timeout-minutes: 10
    permissions: {}
    needs:
      - build
    steps:
      - run: exit 1
  build:
    uses: ./.github/workflows/wc-deploy.yaml
    permissions: {}
    with:
      is_deploy: false
