name: pull request
on: pull_request
jobs:
  status-check:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
