name: pull request
on: pull_request
jobs:
  status-check:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
