---
name: renovate-config-validator
on:
  pull_request:
    paths:
      - renovate.json5
      - .github/workflows/renovate-config-validator.yaml
jobs:
  status-check:
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false
          sparse-checkout-cone-mode: false
          sparse-checkout: |
            renovate.json5
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@c22827f47f4f4a5364bdba19e1fe36907ef1318e # v1.1.1
