name: Deploy
on:
  workflow_call:
    inputs:
      is_deploy:
        required: true
        type: 'boolean'
    secrets:
      APP_ID:
        required: false
      APP_PRIVATE_KEY:
        required: false
jobs:
  deploy:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    permissions: {}
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false
      - uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: '22'
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Generate token
        id: generate_token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2.1.0
        if: inputs.is_deploy
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          repositories: >-
            [
              "github-comment"
            ]
          permissions: >-
            {
              "contents": "write"
            }

      - uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        if: inputs.is_deploy
        with:
          personal_token: ${{ steps.generate_token.outputs.token }}
          external_repository: suzuki-shunsuke/github-comment
          publish_dir: ./build
          destination_dir: ./docs
